/*
@TargetNode='localhost'
@GeneratedBy=admbada
@GenerationDate=11/11/2021 21:22:35
@GenerationHost=DEV-01
*/

instance of DscClass as $DscClass1ref
{
ModuleVersion = "1.0";
 ResourceID = "[DscClass]RefName";
 Path = "C:\\Users\\admbada\\Code\\local\\Concept\\start.ps1";
 SourceInfo = "::6::9::DscClass";
 Ensure = "Present";
 ModuleName = "DscClass";
 ConfigurationName = "PolicyDscClass";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="admbada";

                        GenerationDate="11/11/2021 21:22:35";

                        GenerationHost="DEV-01";

                        Name="PolicyDscClass";

                    };
